resources:
  - name: cacheCreatedWebhookRes
    type: IncomingWebhook
    configuration:
      webhookName: sw_curate_iw
 
pipelines:
  - name: scan_copy
    steps:
    - name: read_webhook_payload
      type: Bash
      configuration:
        inputResources:
          - name: cacheCreatedWebhookRes
      execution:
          onExecute:
            - echo "$res_cacheCreatedWebhookRes_payload" | jq '.' > payload.json
            - cat payload.json
