resources:
  - name: cacheCreatedWebhookRes
    type: IncomingWebhook
    configuration:
      webhookName: curation_webhook
 
pipelines:
  - name: scan_copy
    steps:
    - name: read_webhook_payload
      type: Bash
      configuration:
        inputResources:
          - name: cacheCreatedWebhookRes
      execution:
          onExecute:
            - echo "$res_MyIncomingWebhookResource_payload" | jq '.' > payload.json
            - read_json payload.json "LESSER_SECRET_FORMULA"
            - echo payload.json